// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcwspxquywsssaqerenp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjd3NweHF1eXdzc3NhcWVyZW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NzU3NjcsImV4cCI6MjA2MzA1MTc2N30.QgVT8bqlCL5dJFT1GSZGVfIZ8RgKkLeTwpcCYS5DO9A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);